import { Poppins } from 'next/font/google'
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
      
    </html>
  );
}
